### ISSUE TITLE
Can't get this to run on Nvidia GPU

### ISSUE THREAD

**Issue by Alkaris** [djm34/skminer#1]
for some reason I can't get SK Miner to use my Nvidia card's CUDA GPU. It's a GeForce GT 630M with 96 CUDA Cores.

I run skminer and all I get is this;

```
./skminer 127.0.0.1 1 10
        ***** skMiner for nVidia GPUs by djm34  *****
	             This is version v0.3 
	based on ccMiner by Christian Buchner and Christian H. 2014 ***
                   and on primeminer by Videlicet
	 Copyright 2014 djm34
	  BTC donation address: 1NENYmxwZGHsKFmyjTc5WferTn5VTFb7Ze
	                   CSD: 2S2pCpRXyb8Lpre52U3Xjq2MguSdaea5YGjVTsJqgZBfL2S24ag
cards asked 1
you wish you had those cards... 
```

This is really annoying there's not enough documentation for Linux when it shouldn't sufficiently well documented. Even changed a few things in the Makefile to match my GPU Card for NVCC.

I've seen people say I can just do `./skminer <IP> <port> <card> <core>` and it'll run just fine, but that doesn't seem to be the case here. I don't even think that is even the right command at all for running this, there's no to much as even a `--help` command flag or file.

**Comment by djm34** [comment]
Your card is not supported. Time to upgrade

**Comment by Alkaris** [comment]
Rather bullshit shitty answer just to say _'upgrade'_ or _'not supported'_ when it clearly is capable of using CUDA cores, no matter how little it may actually have. 96 CUDA cores is capable of doing things.

**Comment by djm34** [comment]
well if it is your way to ask me to work on it, it isn't the best way... 
and again it is a bad idea to mine with a laptop (because the cooling isn't appropriate).
and 96 cuda isn't a lot these days... so you'll just spending electricity for nothing

**Comment by Alkaris** [comment]
Not asking you to work on it, nor am I asking you to worry about cooling or
whether you think its a good or bad idea to mine with a laptop or cost of
electricity. I'm asking that you have more appropriate documentation to go
with it so it makes more sense how to actually use this. The number of
times I come across stuff like this where its not documented properly is
the most annoying thing ever because the devs were just simply too
arrogantly lazy to make them and simply expect others to randomly figure
them out.

**Comment by djm34** [comment]
there are forum for your rant and trolling... go there, you'll probably find explanation as well...
(and speaking of being arrogant... sorry but re-read yourself)

**Comment by Alkaris** [comment]
Riiiight, okay, fuck off dude, you be an arrogant fuck now. k. Bye.

**Comment by Alkaris** [comment]
Be the arrogant fuck you are, just like the others.

**Comment by djm34** [comment]
well, if you behave like that with all the "others" dev... may-be the problem is the way you talk to "us"
